#!/usr/bin/env bash

echo "CUCUMBER_ASSEMBLY=${CUCUMBER_ASSEMBLY}"
if [[ ${CUCUMBER_ASSEMBLY} =~ React ]]; then
    node node_modules/.bin/cucumber-electron "$@"
else
    node node_modules/.bin/cucumber.js "$@"
fi
